name: CI

on: [push, pull_request]

jobs:
  job_test_gem:
    name: Test in source tree
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            ruby: "head"
          - os: windows
            ruby: "2.4"
          - os: ubuntu
            ruby: "head"
          - os: ubuntu
            ruby: "3.1"
          - os: ubuntu
            ruby: "2.3"
          - os: macos
            ruby: "head"

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}      # passed to ruby/setup-ruby
          apt-get: "libldap-dev libsasl2-dev" # Ubuntu
          brew: "openldap cyrus-sasl"     # macOS
          mingw: "openldap cyrus-sasl"   # Windows mingw / mswin /ucrt

      - name: Print tool versions
        run: |
          ruby -v
          gcc -v
          gem env

      - name: Bundle install
        run: bundle install

      - name: Run tests
        run: bundle exec rake
